/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author trana
 */
public class EditArea extends javax.swing.JPanel {

    /**
     * Creates new form editArea
     */
    private final Controller.EditAreaController controller;

    public EditArea() {
        initComponents();
        this.controller = new Controller.EditAreaController(this);
        setMinimumSize(new java.awt.Dimension(Controller.Config.col*Controller.Config.cellSize, Controller.Config.row*Controller.Config.cellSize));
        setPreferredSize(new java.awt.Dimension(Controller.Config.col*Controller.Config.cellSize, Controller.Config.row*Controller.Config.cellSize));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");
        jPopupMenu1.add(jMenuItem1);

        setBackground(new java.awt.Color(168, 198, 230));
        setMinimumSize(new java.awt.Dimension(825, 550));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(825, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 825, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        //draw backGround
        drawGridBackGround(g);
        //draw Map
        drawMap(g);
        //draw cell focus
        drawCursor(g);
    }

    private void drawGridBackGround(Graphics g) {
        controller.drawGridBackGround(g);
    }

    private void drawCursor(Graphics g) {
        controller.drawCursor(g);
    }

    private void drawMap(Graphics g) {
        controller.drawMap(g);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables
}
