/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author trana
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        UsetempPanel = new javax.swing.JPanel();
        editArea1 = new View.EditArea();
        MenuBar = new javax.swing.JMenuBar();
        MenuFile = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        MenuOpen = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        MenuSave = new javax.swing.JMenuItem();
        MenuSaveAs = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        MenuExit = new javax.swing.JMenuItem();
        About = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Build Map Tool 1.0");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(940, 600));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.X_AXIS));

        jScrollPane1.setMaximumSize(new java.awt.Dimension(4000, 4000));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(170, 600));
        jScrollPane1.setName(""); // NOI18N
        jScrollPane1.setPreferredSize(new java.awt.Dimension(170, 600));

        UsetempPanel.setBackground(new java.awt.Color(255, 255, 255));
        UsetempPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Usetemp", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        UsetempPanel.setMaximumSize(new java.awt.Dimension(150, 1000));
        UsetempPanel.setMinimumSize(new java.awt.Dimension(150, 596));
        UsetempPanel.setName(""); // NOI18N
        UsetempPanel.setPreferredSize(new java.awt.Dimension(150, 596));

        javax.swing.GroupLayout UsetempPanelLayout = new javax.swing.GroupLayout(UsetempPanel);
        UsetempPanel.setLayout(UsetempPanelLayout);
        UsetempPanelLayout.setHorizontalGroup(
            UsetempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        UsetempPanelLayout.setVerticalGroup(
            UsetempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(UsetempPanel);
        UsetempPanel.getAccessibleContext().setAccessibleName("");
        UsetempPanel.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(jScrollPane1);

        editArea1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout editArea1Layout = new javax.swing.GroupLayout(editArea1);
        editArea1.setLayout(editArea1Layout);
        editArea1Layout.setHorizontalGroup(
            editArea1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 796, Short.MAX_VALUE)
        );
        editArea1Layout.setVerticalGroup(
            editArea1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
        );

        getContentPane().add(editArea1);

        MenuBar.setAlignmentX(1.0F);
        MenuBar.setAlignmentY(0.5F);
        MenuBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        MenuFile.setText("File");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("New");
        MenuFile.add(jMenuItem2);

        MenuOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_0, java.awt.event.InputEvent.CTRL_MASK));
        MenuOpen.setText("Open");
        MenuFile.add(MenuOpen);
        MenuFile.add(jSeparator2);

        MenuSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        MenuSave.setText("Save");
        MenuFile.add(MenuSave);

        MenuSaveAs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        MenuSaveAs.setText("Save As ...");
        MenuFile.add(MenuSaveAs);
        MenuFile.add(jSeparator1);

        MenuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        MenuExit.setText("Exit");
        MenuFile.add(MenuExit);

        MenuBar.add(MenuFile);

        About.setText("Help");

        jMenuItem1.setText("About");
        About.add(jMenuItem1);

        MenuBar.add(About);

        setJMenuBar(MenuBar);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu About;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenuItem MenuExit;
    private javax.swing.JMenu MenuFile;
    private javax.swing.JMenuItem MenuOpen;
    private javax.swing.JMenuItem MenuSave;
    private javax.swing.JMenuItem MenuSaveAs;
    private javax.swing.JPanel UsetempPanel;
    private View.EditArea editArea1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
